/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class Display extends javax.swing.JPanel {

  /**
   * Creates new form Display
   */
  public Display() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    jPanel1.setLayout(new java.awt.GridLayout());

    jLabel2.setText("BP1");
    jPanel1.add(jLabel2);

    jLabel1.setText("BP2");
    jPanel1.add(jLabel1);

    jLabel8.setText("BP3");
    jPanel1.add(jLabel8);

    jLabel9.setText("BP3");
    jPanel1.add(jLabel9);

    add(jPanel1, java.awt.BorderLayout.PAGE_END);

    jPanel3.setLayout(new java.awt.GridLayout(3, 2));

    jLabel3.setText("Current Price:");
    jPanel3.add(jLabel3);

    jLabel4.setText("Highest Bidder:");
    jPanel3.add(jLabel4);

    jLabel5.setText("Time Remaining:");
    jPanel3.add(jLabel5);

    add(jPanel3, java.awt.BorderLayout.CENTER);

    jPanel2.setLayout(new java.awt.GridLayout());

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel6.setText("Currently Bidding on:");
    jPanel2.add(jLabel6);

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel7.setText("650-777-777");
    jPanel2.add(jLabel7);

    add(jPanel2, java.awt.BorderLayout.NORTH);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
}
